#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=50

start() {
	config_load unfsd
	local enabled anon_root write_enable
	config_get enabled  main enabled
	config_get anon_root  main anon_root
	config_get write_enable  main write_enable
	
  if [ $write_enable -eq 1 ]; then
    write_enable="rw"
  else
    write_enable="ro"
  fi
  
  echo "$anon_root    ($write_enable,all_squash,insecure)" > /etc/exports
  
  #if [ $enabled -eq 1 ]; then
    service_start /usr/sbin/unfsd
  #fi
}

stop() {
	service_stop /usr/sbin/unfsd
}

restart() {
	stop;sleep 2;start
}


